language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

env:
  global:
    - COMPOSER_FLAGS="--prefer-stable"

php:
  - 7.2
  - 7.3

matrix:
  include:
    - script: vendor/bin/phpcs -n
      env: PHPCS_BUILD=1

    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: SYMFONY_VERSION="^4.0"

    - php: 7.3
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.3
      env: SYMFONY_VERSION="^4.0"

  allow_failures:
    - php: 7.2
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="dev-master"
    - php: 7.3
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="dev-master"

before_install: if [[ "$SYMFONY_VERSION" != "" ]]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi

install: composer update $COMPOSER_FLAGS --prefer-dist

script: vendor/bin/phpunit
